### ISSUE TITLE
getting Websocket closed 4004

### ISSUE THREAD

**Issue by najshot** [hanyaah/TkPublic#8]
Hello, I'm trying to setup the bot on a ubuntu 16.04 vps

I've installed every dependency correctly or so I assume, I've setup an app and a bot (already invited it to my server), got the token and pasted it to the token.txt file

this is the traceback I get:

> Traceback (most recent call last):
  File "TekkenBot.py", line 241, in <module>
    bot.run(token)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 519, in run
    self.loop.run_until_complete(self.start(*args, **kwargs))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 491, in start
    yield from self.connect()
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 448, in connect
    yield from self.ws.poll_event()
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 437, in poll_event
    raise ConnectionClosed(e) from e
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 4004, reason = Authentication failed..

Could I get some feedback on what I'm missing? not much of a python guru :)

**Comment by hanyaah** [comment]
Did you reset your token while the bot was running by generating a new token?

**Comment by najshot** [comment]
no, This is a fresh instance of the vps, just configured everything went to the discord apps set up the bot and copied the token then pasted it into the file and run the bot with python3 TekkenBot.py

**Comment by hanyaah** [comment]
Try generating a new token and running using that, and see what happens. 

Authentication failed indicates that your token is invalid, which can happen due to you resetting the token, or Discord itself resetting it due to the bot spamming the API.

**Comment by najshot** [comment]
The token changes every time I try to run the bot (launching bot - refreshing page, revealing token -> token is different), I've already regenerated it a couple of times (never during the launch tho)

I've used this tutorial on setting things up
https://github.com/reactiflux/discord-irc/wiki/Creating-a-discord-bot-&-getting-a-token

am I missing something? 
do I need to setup the whole ouath2 thing with the redirect url?

the bot already sits as offline in my server 
http://i.imgur.com/Iw3b1bE.png

**Comment by hanyaah** [comment]
The token does change each time you refresh the page, that's normal. As long as the token isn't reset, all tokens will be valid.

It's only by clicking generating a new token that the algorithm for generating token gets changed, thus invalidating all old tokens.

Just to be sure, the error is occurring on startup, immediately when you try to run the bot?

**Comment by hanyaah** [comment]
Hold on, I think I get what's going on now, haha.

I forgot to specify in the readme that the bot runs by reading from a text file named token.txt in the same directory as tekkenbot.py. My bad.

You'll need to paste your token into a txt file and save it as token.txt in the same directory.

However, if you're already storing your token in a txt file that was created in ubuntu, it might be getting corrupted by linux adding extra characters and file endings to it. In that case, create the file in windows and use FTP to transfer it into your instance.

**Comment by najshot** [comment]
Thanks hanyaah the issue was solved I didn't think of file endings under ubuntu - created the token file in windows and just pushed it to my server. 👍  thanks a lot for help
